#https://external-secrets.io/latest/provider/hashicorp-vault/ Auth can be tricky part..TBD
#
#e.g. "vault kv put secret/foo my-value=s3cr3t"

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend  # Change this to actual clustersecretstore name
    kind: SecretStore
  target:
    name: example-sync   # This will be the name of secret getting created
  data:
  - secretKey: foobar    # This is the secret key
    remoteRef:
      key: foo           # This is the name of key in vault
      property: my-value # This is the pointer to actaul secret value
