# vault kv put kv/sandbox/argocd slack-token=s3cr3tv@lue - from vault pod
# vault kv get kv/sandbox/argocd - from vault pod
#
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault-internal:8200" # vault svc address, check namespace and service type
      path: "kv" # this is imp
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: aHZzLg== # "base64 encoded root vault token"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notification-cm-externalsecret
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend  # Change this to actual clustersecretstore name
    kind: SecretStore
  target:
    name: argocd-notifications-secret   # This will be the name of secret getting created, override default argo secret
  data:
  - secretKey: slack-token    # This is the secret key
    remoteRef:
      key: kv/sandbox/argocd    # This is the name of key in vault, check path in secretstore as well
      property: slack-token # This is the pointer to actaul secret value
